version: 1
builder:
  configs:
    - documentation_targets: 
      - KippleCodable
      - KippleCollections
      - KippleCombine
      - KippleFoundation
      - KippleDevice
      - KippleKeychain
      - KippleLocalStorage
      - KippleLogging
