name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test_universal_package_5_3.yml@main
    with:
      scheme: KippleCore
      subcommand: build
    secrets:
      DISCORD_CI_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}
