name: Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift_test:
    uses: bdrelling/ci/.github/workflows/swift_test.yml@main
    secrets:
      DISCORD_CI_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}
    with:
      scheme: KippleFoundation
      subcommand: build
      platforms: macOS # iOS macOS tvOS watchOS Linux
      # swift-versions: default
      args: --codecov true
      
  upload_coverage:
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    needs: swift_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: bdrelling/Kipple