name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEPLOY_DIRECTORY: deploy
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  prepare:
    name: Prepare
    # Available Runners: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
  swift_build_linux:
    name: swift test (Ubuntu)
    # Available Runners: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    # Available Docker Images: https://hub.docker.com/_/swift/
    container: swift:5.6
    needs: [prepare]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swift Build
        run: swift build
  swift_build_macos:
    name: swift test (macOS)
    # Available Runners: https://github.com/actions/virtual-environments
    runs-on: macos-12
    needs: [prepare]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swift Build
        run: swift build
